// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdqhwczmwwvmbvljgxve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkcWh3Y3ptd3d2bWJ2bGpneHZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2OTk5ODUsImV4cCI6MjA2NjI3NTk4NX0.3iKnYmQp3brLsfd_EcaWeazQMiUVvjQ8Dp5UbGwQf90";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);